volumes:
  mongodb_data_for_app:
    driver: local


services:
  app:
    build: .
    environment:
      ROCKET_CHAT_USER: ${ROCKET_CHAT_USER}
      ROCKET_CHAT_PASSWORD: ${ROCKET_CHAT_PASSWORD}
      ROCKET_CHAT_URL: ${ROCKET_CHAT_URL}
      MONGO_URL_FOR_APP: ${MONGO_URL_FOR_APP}
    depends_on:
      - mongodb_for_app
  
  mongodb_for_app:
    image: mongo:8.0
    volumes:
      - mongodb_data_for_app:/data/db