volumes:
  mongodb_data:
    driver: local


services:
  app:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ROCKET_CHAT_USER: ${ROCKET_CHAT_USER}
      ROCKET_CHAT_PASSWORD: ${ROCKET_CHAT_PASSWORD}
      ROCKET_CHAT_URL: ${ROCKET_CHAT_URL}
      MONGO_URL_FOR_APP: ${MONGO_URL_FOR_APP}
      ENV_TYPE: ${ENV_TYPE}
      PRIVILIGED_ROLES: ${PRIVILIGED_ROLES}
    volumes:
      - ./logs:/logs
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:8.0
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017" 
