volumes:
  mongodb_data:
    driver: local
  app_logs:
    driver: local


services:
  app:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - app_logs:/logs
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:8.0
    volumes:
      - mongodb_data:/data/db
