name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: python:3.13-slim
    steps:
      - uses: actions/checkout@v4
        name: Check commits
        with:
          fetch-depth: 0

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Run chat
#        run: |
#          make chat-compose-up0

#      - name: Run bot
#          make chat-compose-up
