name: CI

on:
  push:
    branches:
      - '*'
      - '!*reports*'
  pull_request:
    branches:
      - '*'
      - '!*reports*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check commits
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13' 
      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run chat
        run: |
          make chat-compose-up0

      - name: Run bot
          make chat-compose-up
