name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check commits
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13' 

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check branch name
        id: check_branch
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          if [[ "$BRANCH_NAME" == *"reports"* ]]; then
            echo "Skipping CI for branch: $BRANCH_NAME"
            exit 1
          fi

      - name: Run chat
        run: |
          make chat-compose-up0

      - name: Run bot
        run: |
          make chat-compose-up
