name: CI

on:
  push:
    branches:
      - main  # Укажите вашу основную ветку
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run chat services
        run: |
          make chat-compose-up
          make load-chat-dump
          make bot-compose-up

      - name: Run integration tests
        run: |
          python test_integration.py  # Убедитесь, что ваш тестовый файл называется именно так