name: Python Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint
      - name: Run Black check
        run: python tests/test_black.py

      - name: Run Pylint analysis
        run: python tests/test_static.py