name: Python functional

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run chat services
        run: |
          cp .env.example .env
          make chat-compose-up
          make load-chat-dump
          make bot-compose-up

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests time datetime pytz

      - name: Run functional tests
        run: |
          python test_functional.py 